flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/MailOnline/bloodhound
    commit: a3ae646f4c8eaf70885b65db1f8e7d0858382b25
  extra-dep: true
extra-deps:
- data-default-generics-0.3
resolver: lts-6.0
